---
- hosts: 192.168.1.53
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Crear página de prueba
      copy:
        content: "<html><head><title>Test Ansible exitoso!</title></head><body><h1>Test Ansible exitoso!</h1></body></html>"
        dest: /var/www/html/index.html
