---
- hosts: 192.168.1.53
  become: yes
  vars:
    mysql_root_password: 'pass123'
    mysql_db: 'wordpress'
    mysql_user: 'admin'
    mysql_password: 'pass123'
  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Instalar el servidor LAMP
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - php-cli

    - name: Instalar el módulo PyMySQL
      pip:
        name: pymysql

    - name: Crear la base de datos de WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present

    - name: Crear el usuario de WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present

    - name: Instalar Python pip (necesario para instalar 'python-mysqldb')
      apt:
        name: python-pip
        state: present

    - name: Instalar 'python-mysqldb' (necesario para usar 'mysql_db' y 'mysql_user')
      pip:
        name: python-mysqldb

    - name: Instalar WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Actualizar el archivo de configuración de WordPress con las credenciales de la base de datos
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: "define\\('DB_NAME', 'database_name_here'\\);", replace: "define('DB_NAME', '{{ mysql_db }}');" }
        - { regexp: "define\\('DB_USER', 'username_here'\\);", replace: "define('DB_USER', '{{ mysql_user }}');" }
        - { regexp: "define\\('DB_PASSWORD', 'password_here'\\);", replace: "define('DB_PASSWORD', '{{ mysql_password }}');" }

    - name: Reiniciar Apache para que los cambios tengan efecto
      service:
        name: apache2
        state: restarted
