---
- name: Instalar aplicaciones y reiniciar
  hosts: 192.168.1.52
  tasks:
    - name: Descargar Google Chrome
      win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\Users\Administrador\Downloads\ansible\chrome_installer.exe

    - name: Instalar Google Chrome
      win_package:
        path: C:\Users\Administrador\Downloads\ansible\chrome_installer.exe
        state: present

    - name: Descargar WinSCP
      win_get_url:
        url: https://winscp.net/download/WinSCP-5.17.10-Setup.exe
        dest: C:\Users\Administrador\Downloads\ansible\WinSCP-5.17.10-Setup.exe

    - name: Instalar WinSCP
      win_package:
        path: C:\Users\Administrador\Downloads\ansible\WinSCP-5.17.10-Setup.exe
        state: present

    - name: Descargar PuTTY
      win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.76-installer.msi
        dest: C:\Users\Administrador\Downloads\ansible\putty-64bit-0.76-installer.msi

    - name: Instalar PuTTY
      win_package:
        path: C:\Users\Administrador\Downloads\ansible\putty-64bit-0.76-installer.msi
        state: present

    - name: Descargar Notepad++
      win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.3.2/npp.8.3.2.Installer.x64.exe
        dest: C:\Users\Administrador\Downloads\ansible\npp.8.3.2.Installer.x64.exe

    - name: Instalar Notepad++
      win_package:
        path: C:\Users\Administrador\Downloads\ansible\npp.8.3.2.Installer.x64.exe
        state: present

    - name: Descargar WinRAR
      win_get_url:
        url: https://www.rarlab.com/rar/winrar-x64-602.exe
        dest: C:\Users\Administrador\Downloads\ansible\winrar-x64-602.exe

    - name: Instalar WinRAR
      win_package:
        path: C:\Users\Administrador\Downloads\ansible\winrar-x64-602.exe
        state: present

    - name: Reiniciar el servidor
      win_reboot:
        reboot_timeout: 300
        msg: "Reiniciando el servidor después de instalar las aplicaciones"
