---
- name: Instalar aplicaciones y reiniciar
  hosts: 192.168.1.52
  tasks:
    - name: Descargar Google Chrome
      win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\Users\Administrador\Downloads\ansible\chrome_installer.exe

    - name: Instalar Google Chrome
      win_shell: Start-Process -FilePath C:\Users\Administrador\Downloads\ansible\chrome_installer.exe -Args '/silent /install' -NoNewWindow -Wait
      
    - name: Descargar PuTTY
      win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.81-installer.msi
        dest: C:\Users\Administrador\Downloads\ansible\putty-64bit-0.81-installer.msi

    - name: Instalar PuTTY
      win_shell: Start-Process -FilePath C:\Users\Administrador\Downloads\ansible\putty-64bit-0.81-installer.msi -Args '/silent /install' -NoNewWindow -Wait

    - name: Descargar Notepad++
      win_get_url:
        url: https://notepad-plus-plus.org/downloads/v8.6.5/
        dest: C:\Users\Administrador\Downloads\ansible\npp.8.6.5.Installer.x64.exe

    - name: Instalar Notepad++
      win_shell: Start-Process -FilePath C:\Users\Administrador\Downloads\ansible\npp.8.6.5.Installer.x64.exe -Args '/silent /install' -NoNewWindow -Wait

    - name: Descargar WinRAR
      win_get_url:
        url: https://www.win-rar.com/download.html
        dest: C:\Users\Administrador\Downloads\ansible\winrar-x64-7.00.exe

    - name: Instalar WinRAR
      win_shell: Start-Process -FilePath C:\Users\Administrador\Downloads\ansible\winrar-x64-7.00.exe -Args '/silent /install' -NoNewWindow -Wait

    - name: Reiniciar el servidor
      win_reboot:
        reboot_timeout: 300
        msg: "Reiniciando el servidor después de instalar las aplicaciones"
